{
    "2": "Bullet Sign \"Eagle Shooting\"",
    "3": "Rabbit Sign \"Strawberry Big Dango\"",
    "4": "Bullet Sign \"Rabbit Falconer\"",
    "5": "Rabbit Sign \"Dango Three Sisters\"",
    "7": "Butterfly Sign \"Butterfly Dream\"",
    "8": "Butterfly Sign \"Coiling Scales\"",
    "10": "Magic Sign \"Jizo of Mercy\"",
    "11": "Jizo \"Bodhisattva Stomp\"",
    "12": "Jizo \"Lively Meatball Golem\"",
    "14": "Sharpening Sign \"Madly Glinting Oni Kitchen Knife\"",
    "15": "Murder Sign \"Deeply-Secluded Yamanba\"",
    "17": "Spinning Top \"Koma-inu Slalom Spin\"",
    "18": "Spinning Top \"A-Um Flash\"",
    "21": "Dream Bullet \"Lunatic Dream Shot\"",
    "22": "Dango \"Dango Flower\"",
    "23": "Dream Butterfly \"Crazy Butterfly\"",
    "24": "Dream Jizo \"Hope of Calamitous Fire\"",
    "25": "Dream Exhaustion \"Serial Killer's Hideaway\"",
    "26": "Dream Dog \"101 Stray Dogs\"",
    "28": "Hell Sign \"Bursting Grudge\"",
    "29": "Hell Sign \"Double Stripe\"",
    "30": "Meatball Dream \"Eclipse Nightmare\"",
    "32": "Orb Sign \"Impregnable Fortress' Yin-Yang Orbs\"",
    "33": "Orb Sign \"Hard-to-Photograph Shotgun Coronation of the Gods\"",
    "34": "Dream Heron \"One-Winged Dream Heron\"",
    "36": "Bamboo Sign \"Bamboo Labyrinth\"",
    "37": "Myōga Ginger \"Mesmerism Dance\"",
    "38": "Broadleaf Sign \"Tanabata Star Dream\"",
    "39": "Myōga Blessing \"Behind Nightmare\"",
    "41": "Otherworld \"Distorted Fire\"",
    "42": "Otherworld \"Resentful Rain of Hell\"",
    "43": "Moon \"Cosmic Radiation\"",
    "44": "Otherworld \"Ōmagatoki -Dream-\"",
    "45": "\"The Meatball is Falling!\"",
    "47": "\"Trembling, Shivering Nightmare\"",
    "48": "\"Psychedelic Mandala\"",
    "49": "\"Pure Light with Extreme Majesty\"",
    "50": "\"The Danmaku for a Conclusive Murder through Nightmares\"",
    "51": "Secret Ceremony \"Matarah Sukha\"",
    "52": "Secret Ceremony \"The Rear Face's Wicked Flames\"",
    "53": "Back Sign \"Halo of the Absolute Secret God\"",
    "54": "Secret Ceremony \"Secret God's Covert Danmaku\"",
    "55": "Secret Ceremony \"Arcane Dupion\"",
    "57": "Scarlet Devil Sign \"Bloody Catastrophe\"",
    "61": "Divine Scarlet Sign \"Bloody Laser of Seventeen Articles\"",
    "62": "Scarlet Star Sign \"Superhuman Catastrophe Pilgrimage\"",
    "64": "Wind God Sign \"Mishabashira\"",
    "66": "Wind Flower Sign \"Mishaguji-sama's Right and Wrong\"",
    "68": "Wind Flower Sign \"Onbashira Judgment\"",
    "72": "Shining Night Sign \"Big Bullet Branch of Hourai\"",
    "70": "Scarlet Needle Sign \"Keystones, Grow Bigger!\"",
    "69": "Eternal Night Sign \"Bullet Branch of Hourai in a Pot\"",
    "74": "Scarlet Night Sign \"Bullet Keystones of Hourai\"",
    "75": "Earth Spirit Sign \"Mind Stellar Steal\"",
    "76": "Earth Mystic Sign \"Shikigami of the Id\"",
    "77": "\"Perfect Mind Control\"",
    "78": "Earth Mystic Sign \"Shikigami's Giant Star\"",
    "80": "Earth Spirit Sign \"Mind Stellar Relief\"",
    "81": "Divine Star Sign \"Unidentified Ghost-Light Crowd\"",
    "82": "Shining Heaven Sign \"Thunderclap Spaghetti Drum\"",
    "83": "Shining Divine Sign \"Mysterious Spaghetti Crowd\"",
    "84": "Scarlet Star Sign \"Unidentified Lightning Strike\"",
    "85": "Divine Scarlet Sign \"Stalker in a Thunderstorm\"",
    "86": "Shining Star Sign \"Unidentified Spaghetti Drum\"",
    "87": "Gathering Night Sign \"Precious Life Scatters like Mist\"",
    "88": "Ultramarine Orb Sign \"Pure and Impure Danmaku\"",
    "91": "Gathering Orb Sign \"Mist Ray\"",
    "92": "Eternal Orb Sign \"An Unsullied Orb and a Much-Sullied Spirit\"",
    "93": "\"Secret God Barrier\"",
    "96": "\"Shoot the Danmaku Barrier!\"",
    "94": "\"Sneak-Photographer Exorcism Master Spark\"",
    "99": "\"The Nightmare One Has on Their Final Sunday\"",
    "100": "Paper Sign \"Zener Card Shuriken\"",
    "101": "Paper Sign \"Barrier-Enclosed Zener Card Shuriken\"",
    "58": "Star God Sign \"Superhuman of 17 Articles\"",
    "59": "Scarlet Star Sign \"Superhuman's Bloody Knife\"",
    "60": "Scarlet God Sign \"Seventeen-article Catastrophe\"",
    "63": "Mystic Flower Sign \"Buffterfly Storm Yama Rod\"",
    "65": "Wind Mystic Sign \"Dead Butterfly Onbashira\"",
    "67": "Mystic Wind Sign \"Native Butterfly Storm\"",
    "71": "Eternal Crimson Sign \"Falling Bhavaagra in a Pot\"",
    "73": "[Unnamed Eirin & Shinmyoumaru Spell]",
    "79": "Earth Mystic Sign \"Shikigami of the Ego\"",
    "89": "Gathering Orb Sign \"In Pure Miles of Mists\"",
    "90": "Eternal Orb sign \"Sacrificial Reflection\"",
    "95": "\"Punish Peeping Tom from the Back\"",
    "97": "\"Cunning Master Spark\"",
    "98": "\"Consented Danmaku Photo Only\""
}